apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}
  labels:
    app: {{.Values.appName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{.Values.appName}}
          image: "{{.Values.repository}}/{{.Values.imageName}}:{{ .Values.imageTag }}"
          ports:
            - containerPort: 3000
      {{if .Values.imagePullSecret }}             
      imagePullSecrets:
        - name: {{.Values.imagePullSecret}}              
      {{ end }}