apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}-service
spec:
  selector:
    app: {{.Values.appName}}
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000