config:
  namespace: frontend


microservice:
  image:
    imageTag: dev-15
    
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
    hosts:
      - host: frontend.argouniverse.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: 
    - secretName: issuer-letsencrypt-frontend
      hosts:
        - frontend.argouniverse.com